sms/src/AppBundle/Entity/Document.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Document
 *
 * @ORM\Table(name="sns_document")
 * @ORM\Entity
 */
class Document
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;


    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="createdAt", type="datetimetz")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update") 
     * @ORM\Column(name="updatedAt", type="datetimetz")
     */
    private $updatedAt;    
    
    public function getFullClassName()
    {
      return get_class($this);
    }
    
    public function retrieveAlbums()
    {
      return array('documents');
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Document
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Document
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Document
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
}

sms/src/AppBundle/Form/DocumentType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DocumentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            //->add('imageName')
            /*
            ->add('imageName', 'vich_file', array(
              'required'      => false,
              'allow_delete'  => true, // not mandatory, default is true
              'download_link' => true, // not mandatory, default is true
              'label'         => 'Upload CV',
            ))       
              */  
            //->add('updatedAt')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Document'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'appbundle_document';
    }
}

sms/src/AppBundle/Controller/DocumentController.php
<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use AppBundle\Entity\Document;
use AppBundle\Form\DocumentType;

/**
 * Document controller.
 *
 */
class DocumentController extends Controller
{

    /**
     * Lists all Document entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('AppBundle:Document')->findAll();

        return $this->render('AppBundle:Document:index.html.twig', array(
            'entities' => $entities,
        ));
    }
    /**
     * Creates a new Document entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity = new Document();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('admin_document_edit', array('id' => $entity->getId())));
        }

        return $this->render('AppBundle:Document:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Document entity.
     *
     * @param Document $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Document $entity)
    {
        $form = $this->createForm(new DocumentType(), $entity, array(
            'action' => $this->generateUrl('admin_document_create'),
            'method' => 'POST',
        ));

        //$form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Document entity.
     *
     */
    public function newAction()
    {
        $entity = new Document();
        $form   = $this->createCreateForm($entity);

        return $this->render('AppBundle:Document:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Document entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Document')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Document entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('AppBundle:Document:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Document entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Document')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Document entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('AppBundle:Document:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
    * Creates a form to edit a Document entity.
    *
    * @param Document $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Document $entity)
    {
        $form = $this->createForm(new DocumentType(), $entity, array(
            'action' => $this->generateUrl('admin_document_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        //$form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Document entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Document')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Document entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('admin_document_edit', array('id' => $id)));
        }

        return $this->render('AppBundle:Document:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Deletes a Document entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AppBundle:Document')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Document entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('admin_document'));
    }

    /**
     * Creates a form to delete a Document entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_document_delete', array('id' => $id)))
            ->setMethod('DELETE')
            //->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

sms/src/AppBundle/Resources/views/Document/edit.html.twig
{% extends 'AppBundle::adminlayout.html.twig' %}

{% block pagestylesheets %}
  <link rel="stylesheet" type="text/css" href="{{ asset('bundles/maithcommonimage/css/maithalbums.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ asset('bundles/maithcommonadmin/css/colorbox.css') }}" />
{% endblock %}
{% block javascripts %}
  <script type="text/javascript" src="{{ asset('bundles/maithcommonadmin/js/jquery.colorbox-min.js') }}"></script>    
  <script type="text/javascript" src="{{ asset('bundles/maithcommonimage/js/imagesManager.js') }}"></script>    
{% endblock %}

{% block body -%}
<div class="row">
  <div class="col-lg-8">
    <section class="panel">
      <header class="panel-heading">{% trans %}document_update_entry{% endtrans %}</header>
      <div class="panel-body">
        <form action="{{ path('admin_document_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }} role="form">
		  <input type="hidden" name="_method" value="PUT" />  
          <div class="form-group">
              {{ form_errors(edit_form.name) }}
              <label for="{{ edit_form.name.vars.id }}">{% trans %}document_name{% endtrans %}</label>
              {{ form_widget(edit_form.name, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-default">{% trans %}document_save{% endtrans %}</button>
          </div>	
              {{ form_rest(edit_form) }}
          </form>
	  
	  {{ render(controller('MaithCommonAdminBundle:Albums:albumsData', {'id': entity.id, 'objectclass' : entity.fullClassName, 'listmode' : false }))}}
        </div>
      </section>
    </div>
    <div class="col-lg-8">
        <a href="{{ path('admin_document') }}" class="btn btn-info">
		  {% trans %}document_back_to_list{% endtrans %}
	  </a>
		<form action="{{ path('admin_document_delete', { 'id': entity.id }) }}" method="post" onsubmit="return confirmDeleteDialog();" style="float: right;">
		  <input type="hidden" name="_method" value="DELETE" />
			{{ form_widget(delete_form) }}
		  <button class="btn btn-danger" type="submit">{% trans %}document_delete{% endtrans %}</button>
		</form>
	</div>	
    
</div>  
{% endblock %}

sms/src/AppBundle/Resources/views/Document/index.html.twig
{% extends 'AppBundle::adminlayout.html.twig' %}
{% block pagestylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/admin/vendor/chosen/chosen.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('bundles/app/admin/vendor/datatables/jquery.dataTables.css') }}" />
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/admin/vendor/chosen/chosen.jquery.min.js') }}"></script>
    <script src="{{ asset('bundles/app/admin/vendor/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('bundles/app/admin/js/datatables.js') }}"></script>
{% endblock %}

{% block body -%}
<div class="row">
        <div class="col-lg-8">    
            <section class="panel panel-info">
                <header class="panel-heading">{% trans %}document_list_title{% endtrans %}</header>
                <div class="panel-body">
                    <div class="table-responsive no-border">
                        <table class="table table-bordered table-striped mg-t datatable">
                            <thead>
                                <tr>
                                    <th>{% trans %}document_file{% endtrans %}</th>
                                    <th>{% trans %}document_title{% endtrans %}</th>
                                    <th>{% trans %}document_createdat{% endtrans %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for entity in entities %}
                                    <tr>
                                        <td>{{ entity.name }}</td>
                                        <td>{{ entity.createdAt | date('d/m/Y')}}</td>
                                        <td>
                                        <ul>
                                            <li>
                                                <a href="{{ path('admin_document_edit', { 'id': entity.id }) }}"><i class="fa fa-pencil-square-o fa-2x"></i></a>
                                            </li>
                                        </ul>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="col-lg-12 text-center">
                            <a href="{{ path('admin_document_new') }}" class="btn btn-info">
                                {% trans %}document_create{% endtrans %}
                            </a>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>  
    
{% endblock %}

sms/src/AppBundle/Resources/views/Document/new.html.twig
{% extends 'AppBundle::adminlayout.html.twig' %}

{% block body -%}
  
<div class="row">
  <div class="col-lg-6">
    <section class="panel">
      <header class="panel-heading">{% trans %}document_create_entry{% endtrans %}</header>
      <div class="panel-body">
        <form action="{{ path('admin_document_create') }}" method="post" {{ form_enctype(form) }} role="form">
          <div class="form-group">
            {{ form_errors(form.name) }}
            <label for="{{ form.name.vars.id }}">{% trans %}document_name{% endtrans %}</label>
            {{ form_widget(form.name, {'attr' : {'class' : 'form-control'}}) }}
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-default">{% trans %}document_save{% endtrans %}</button>
          </div>	
              {{ form_rest(form) }}
          </form>
        </div>
      </section>
    </div>
    <div class="col-lg-8 text-center">
	  <a href="{{ path('admin_document') }}" class="btn btn-info">
		  {% trans %}document_back_to_list{% endtrans %}
	  </a>
	</div>
</div>
{% endblock %}

sms/src/AppBundle/Resources/views/Document/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Document</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ entity.name }}</td>
            </tr>
            <tr>
                <th>Imagename</th>
                <td>{{ entity.imageName }}</td>
            </tr>
            <tr>
                <th>Updatedat</th>
                <td>{{ entity.updatedAt|date('Y-m-d H:i:s') }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_document') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('admin_document_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}